[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# 优化设置
optimizer = true
optimizer_runs = 200
via_ir = true

# 测试设置
verbosity = 2
fuzz = { runs = 256 }

# 部署设置
[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }

# 格式化
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
